Add infrastucture for testing type inference.
We include a sample test which can demonstrate the failure, which is
currently commented-out. Uncommenting would give:
```
~ mypy once_test.py
once_test.py:691: error: Expression is of type "Any", not "int"  [assert-type]
Found 1 error in 1 file (checked 1 source file)
```